-- Migration: knowledge (user_id, relation) lookup index + updated_at
--
-- APPLIED to the live project (`Sunland Project`, klyrasrqgxijwrxuoevj) on
-- 2026-09-13 as schema_migrations version `20260913014653`
-- (name: add_knowledge_user_relation_idx_and_updated_at). The file name in this
-- repository is a local label; the authoritative identifier is the recorded
-- version above.
--
-- Independent, live-schema-based incremental change. This is NOT a replay of
-- anything under supabase/migrations/ in this repository: no file in this repo
-- is recorded in `supabase_migrations.schema_migrations` on the live project,
-- and migration lineage reconciliation is explicitly out of scope for this
-- change (separate task).
--
-- Purpose (proposal item B3, re-scoped after live recon, + half of B9):
--   1. A per-relation filter (`where user_id = ? and relation = ?`) cannot use
--      any existing index as an access predicate. The knowledge indexes are
--      `(user_id, id)`, `(user_id, created_at, id)` and the unique
--      `(user_id, subject, relation, object, negated)`; `relation` is not a
--      usable prefix of any of them.
--      A per-SUBJECT filter needs no new index: `(user_id, subject)` is the
--      leading prefix of the existing unique constraint's index, which the
--      planner already uses. The originally proposed `(user_id, subject)`
--      index was therefore dropped from this migration as redundant.
--   2. Correcting or re-teaching a fact needs to know when it last changed.
--      `created_at` cannot answer that.
--
-- Scope discipline:
--   - Adds ONE index and ONE nullable-then-backfilled column. Nothing else.
--   - Does NOT touch any RPC, RLS, policy, grant, or legacy table.
--     (The missing `sunland_db_token_profiles` policy is a separately recorded,
--     unresolved drift item and is deliberately NOT addressed here.)
--   - Does NOT change existing rows' knowledge semantics: subject, relation,
--     object, negated, confidence, source and created_at are never rewritten.
--     Historical rows DO get `updated_at` backfilled to equal `created_at`,
--     which is a new column's initial value, not a semantic rewrite.
--   - Does NOT depend on, and does not alter, the deferred legacy RLS gate.
--
-- Safety properties:
--   - Re-runnable: every statement is guarded, so applying it twice is a no-op.
--   - Reversible: supabase/rollback/202609130005_add_knowledge_lookup_indexes_rollback.sql
--   - Pre-flight asserted: aborts loudly if the live table is not the shape this
--     migration was written against, instead of altering something unexpected.
--
-- Ground truth used (read-only recon on the live project, 2026-09-13):
--   - 9 columns, all NOT NULL where expected, no `updated_at` present.
--   - Unique (user_id, subject, relation, object, negated) exists with that
--     column order, under the autogenerated name
--     `sunland_ai_knowledge_user_id_subject_relation_object_negate_key`.
--     This migration matches it by COLUMNS, never by name.
--   - 2 rows, created_at never NULL.
--   - `sunland_commit_turn` inserts with an explicit column list, so a
--     NOT NULL DEFAULT column cannot break live turns.

begin;

-- ---------------------------------------------------------------------------
-- Pre-flight: confirm the live schema still matches the assumption, and refuse
-- to proceed otherwise. A migration that silently adapts to an unknown shape
-- is worse than one that fails.
-- ---------------------------------------------------------------------------
do $$
declare
  v_missing text;
begin
  if to_regclass('public.sunland_ai_knowledge') is null then
    raise exception 'pre-flight failed: public.sunland_ai_knowledge does not exist';
  end if;

  -- Expected columns and their NOT NULL expectation.
  select string_agg(expected.name, ', ')
    into v_missing
    from (values
      ('user_id', true), ('id', true), ('subject', true), ('relation', true),
      ('object', true), ('negated', true), ('confidence', true),
      ('source', true), ('created_at', true)
    ) as expected(name, not_null)
   where not exists (
     select 1
       from information_schema.columns actual
      where actual.table_schema = 'public'
        and actual.table_name = 'sunland_ai_knowledge'
        and actual.column_name = expected.name
        and actual.is_nullable <> 'YES'
   );
  if v_missing is not null then
    raise exception 'pre-flight failed: expected NOT NULL columns missing or nullable: %', v_missing;
  end if;

  -- The primary key and the fact-identity unique constraint must both exist;
  -- this migration must not be used as an opportunity to "fix" either.
  if not exists (
    select 1 from pg_constraint
     where conrelid = 'public.sunland_ai_knowledge'::regclass
       and contype = 'p'
  ) then
    raise exception 'pre-flight failed: primary key not found';
  end if;

  -- Column names in the constraint's own order. `count(*)` keeps this an
  -- aggregate (always exactly one row) so a missing column can never make the
  -- scalar subquery return NULL and slip past.
  if not exists (
    select 1
      from pg_constraint con
     cross join lateral (
       select array_agg(att.attname::text order by k.ord) as names, count(*) as seen
         from unnest(con.conkey) with ordinality as k(attnum, ord)
         join pg_attribute att
           on att.attrelid = con.conrelid
          and att.attnum = k.attnum
     ) cols
     where con.conrelid = 'public.sunland_ai_knowledge'::regclass
       and con.contype = 'u'
       and cols.seen = 5
       and cols.names = array['user_id', 'subject', 'relation', 'object', 'negated']
  ) then
    raise exception 'pre-flight failed: unique (user_id, subject, relation, object, negated) not found';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 1. (user_id, relation) lookup index.
-- `create index if not exists` alone is not enough to be re-runnable: an index
-- created outside this migration under the same name but different from what is
-- intended would be silently accepted. The guard checks the structural
-- properties this migration relies on, without string-matching DDL text.
-- ---------------------------------------------------------------------------
do $$
declare
  v_relid oid;
  v_columns text;
begin
  select c.oid into v_relid
    from pg_class c
   where c.relname = 'sunland_ai_knowledge_user_relation_idx'
     and c.relnamespace = 'public'::regnamespace
     and c.relkind = 'i';

  if v_relid is null then
    return; -- not present yet: the create below will add it
  end if;

  select string_agg(a.attname, ',' order by k.ord)
    into v_columns
    from pg_index i
    cross join lateral unnest(i.indkey) with ordinality as k(attnum, ord)
    join pg_attribute a
      on a.attrelid = i.indrelid
     and a.attnum = k.attnum
   where i.indexrelid = v_relid;

  if exists (select 1 from pg_index where indexrelid = v_relid and not indisvalid)
    or exists (select 1 from pg_index where indexrelid = v_relid and indisunique)
    or exists (select 1 from pg_index where indexrelid = v_relid and indpred is not null)
  then
    raise exception 'pre-flight failed: index sunland_ai_knowledge_user_relation_idx exists but is invalid, unique, or partial';
  end if;

  if v_columns is distinct from 'user_id,relation' then
    raise exception 'pre-flight failed: index sunland_ai_knowledge_user_relation_idx has unexpected columns (%)', v_columns;
  end if;
end;
$$;

create index if not exists sunland_ai_knowledge_user_relation_idx
  on public.sunland_ai_knowledge (user_id, relation);

-- ---------------------------------------------------------------------------
-- 2. `updated_at`, backfilled from `created_at`.
--
-- Backfill and NOT NULL are ordered so the statement is re-runnable and safe on
-- a table with existing rows:
--   add column (nullable) -> backfill -> set not null -> set default.
-- The default is `now()`, so rows written by the existing (unmodified)
-- `sunland_commit_turn` RPC receive a real write time from this point on.
-- ---------------------------------------------------------------------------
alter table public.sunland_ai_knowledge
  add column if not exists updated_at timestamptz;

update public.sunland_ai_knowledge
   set updated_at = created_at
 where updated_at is null;

alter table public.sunland_ai_knowledge
  alter column updated_at set not null;

alter table public.sunland_ai_knowledge
  alter column updated_at set default now();

comment on column public.sunland_ai_knowledge.updated_at is
  'Last write time. Backfilled to created_at for rows that predate this column; defaults to now() afterwards. Maintenance-only: no RPC or policy reads it yet.';

commit;
